services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    LoyaltyCorp\Schedule\ScheduleBundle\Command\ScheduleRunCommand: ~

    LoyaltyCorp\Schedule\ScheduleBundle\DataCollector\ScheduleDataCollector:
        tags:
            -
                name: data_collector
                template: '@Schedule/Collector/schedule_collector.html.twig'
                id: !php/const LoyaltyCorp\Schedule\ScheduleBundle\DataCollector\ScheduleDataCollector::NAME

    LoyaltyCorp\Schedule\ScheduleBundle\Interfaces\LockFactoryProviderInterface:
        class: LoyaltyCorp\Schedule\ScheduleBundle\LockFactoryProvider

    LoyaltyCorp\Schedule\ScheduleBundle\Interfaces\ScheduleInterface:
        class: LoyaltyCorp\Schedule\ScheduleBundle\Schedule

    LoyaltyCorp\Schedule\ScheduleBundle\Interfaces\ScheduleRunnerInterface:
        class: LoyaltyCorp\Schedule\ScheduleBundle\ScheduleRunner
